In [4]:
import pandas as pd

path = "/Users/jayant/Desktop/LifeCost/Scrapping_Manual/cpi/Centre group index   Official website of Labour Bureau, Ministry of Labour and Employment,Government of India.xlsx"

df = pd.read_excel(path)

# Fix column names
df.columns = ["SNo", "BaseYear", "State", "Centre", "Group", "Year", "Month", "Index"]

# Drop header row that got imported as data
df = df[df["BaseYear"] != "Base Year"]

# Convert types
df["Year"] = df["Year"].astype(int)
df["Index"] = pd.to_numeric(df["Index"], errors="coerce")

df.head()

  SNo BaseYear           State  Centre             Group  Year Month  Index
1   1     2016  ANDHRA PRADESH  Guntur  Food & Beverages  2021   Jan  114.9
2   2     2016  ANDHRA PRADESH  Guntur  Food & Beverages  2022   Jan  125.7
3   3     2016  ANDHRA PRADESH  Guntur  Food & Beverages  2023   Jan  141.6
4   4     2016  ANDHRA PRADESH  Guntur  Food & Beverages  2024   Jan  148.0
5   5     2016  ANDHRA PRADESH  Guntur  Food & Beverages  2025   Jan  155.8

In [6]:
bhopal = df[
    (df["Centre"].str.upper() == "bhopal") &
    (df["Group"] == "All Items")
].sort_values(["Year", "Month"])

bhopal.head()

Empty DataFrame
Columns: [SNo, BaseYear, State, Centre, Group, Year, Month, Index]
Index: []

In [7]:
bhopal["Inflation_YoY_%"] = (
    bhopal["Index"].pct_change(12) * 100
).round(2)

bhopal.tail()

ValueError: attempt to get argmax of an empty sequence

In [ ]:
bhopal.to_excel("/mnt/data/bhopal_cpi_clean.xlsx", index=False)
bhopal.to_csv("/mnt/data/bhopal_cpi_clean.csv", index=False)

In [9]:
import pandas as pd

path = "/Users/jayant/Desktop/LifeCost/Scrapping_Manual/cpi/Centre group index   Official website of Labour Bureau, Ministry of Labour and Employment,Government of India.xlsx"

df = pd.read_excel(path, header=None)
print(df.head(10))

                                                   0          1  \
0   Centre group index |  Official website of Lab...        NaN
1                                               S.No  Base Year
2                                                  1       2016
3                                                  2       2016
4                                                  3       2016
5                                                  4       2016
6                                                  5       2016
7                                                  6       2016
8                                                  7       2016
9                                                  8       2016

                2       3                                   4     5      6  \
0             NaN     NaN                                 NaN   NaN    NaN
1           State  Centre                               Group  Year  Month
2  ANDHRA PRADESH  Guntur                    Food & Beverages  2021    Jan
3  ANDHRA PRADESH  Guntur                    Food & Beverages  2022    Jan
4  ANDHRA PRADESH  Guntur                    Food & Beverages  2023    Jan
5  ANDHRA PRADESH  Guntur                    Food & Beverages  2024    Jan
6  ANDHRA PRADESH  Guntur                    Food & Beverages  2025    Jan
7  ANDHRA PRADESH  Guntur  Pan, Supari, Tobacco & Intoxicants  2021    Jan
8  ANDHRA PRADESH  Guntur  Pan, Supari, Tobacco & Intoxicants  2022    Jan
9  ANDHRA PRADESH  Guntur  Pan, Supari, Tobacco & Intoxicants  2023    Jan

       7
0    NaN
1  Index
2  114.9
3  125.7
4  141.6
5    148
6  155.8
7  107.7
8  107.7
9  165.6

In [10]:
df = pd.read_excel(path, header=1)   # try header=1 or header=2 if needed
print(df.columns)
print(df.head())

Index(['S.No', 'Base Year', 'State', 'Centre', 'Group', 'Year', 'Month',
       'Index'],
      dtype='object')
   S.No  Base Year           State  Centre             Group  Year Month  \
0     1       2016  ANDHRA PRADESH  Guntur  Food & Beverages  2021   Jan
1     2       2016  ANDHRA PRADESH  Guntur  Food & Beverages  2022   Jan
2     3       2016  ANDHRA PRADESH  Guntur  Food & Beverages  2023   Jan
3     4       2016  ANDHRA PRADESH  Guntur  Food & Beverages  2024   Jan
4     5       2016  ANDHRA PRADESH  Guntur  Food & Beverages  2025   Jan

   Index
0  114.9
1  125.7
2  141.6
3  148.0
4  155.8

In [14]:
bhopal_df = df[df['Centre'].astype(str).str.strip().str.contains("bhopal", case=False, na=False)]

print(bhopal_df)

      S.No  Base Year           State  Centre             Group  Year Month  \
1470  1471       2016  MADHYA PRADESH  Bhopal  Food & Beverages  2021   Jan
1471  1472       2016  MADHYA PRADESH  Bhopal  Food & Beverages  2022   Jan
1472  1473       2016  MADHYA PRADESH  Bhopal  Food & Beverages  2023   Jan
1473  1474       2016  MADHYA PRADESH  Bhopal  Food & Beverages  2024   Jan
1474  1475       2016  MADHYA PRADESH  Bhopal  Food & Beverages  2025   Jan
...    ...        ...             ...     ...               ...   ...   ...
4580  4581       2016  MADHYA PRADESH  Bhopal     General Index  2021   Feb
4581  4582       2016  MADHYA PRADESH  Bhopal     General Index  2022   Feb
4582  4583       2016  MADHYA PRADESH  Bhopal     General Index  2023   Feb
4583  4584       2016  MADHYA PRADESH  Bhopal     General Index  2024   Feb
4584  4585       2016  MADHYA PRADESH  Bhopal     General Index  2025   Feb

      Index
1470  114.3
1471  119.6
1472  130.1
1473  143.1
1474  140.6
...     ...
4580  115.1
4581  122.8
4582  128.2
4583  134.2
4584  132.7

[70 rows x 8 columns]

In [16]:
bhopal_df.to_excel("/Users/jayant/Desktop/LifeCost/Scrapping_Manual/cpi/bhopal_cpi_clean.xlsx", index=False)